# Generated by Django 5.0.6 on 2024-06-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=30)),
                ('fechaDeClase', models.DateField()),
                ('clase', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClasesAlumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=30)),
                ('clase', models.IntegerField()),
                ('fechaDeClase', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Desafios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desafio', models.CharField(max_length=30)),
                ('fechaLimite', models.DateField()),
                ('completado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('clase', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroInstructores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=30)),
                ('clase', models.IntegerField()),
                ('titulo', models.CharField(max_length=30)),
                ('reseña', models.TextField()),
                ('fechaDeClase', models.DateField()),
            ],
        ),
    ]
